CUDA_ARCH=sm_60
DRIVER_TCCG=driver-tccg
#DEBUG_OPTIONS=-DDEBUG_CORRECTNESS

#
#	TCCG: One of Inputs or Both of Inputs has 1 External Indices (The Others)
#
k_tccg_1: $(DRIVER_TCCG)/code_main_tccg_01.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_01.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_2: $(DRIVER_TCCG)/code_main_tccg_02.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_02.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_3: $(DRIVER_TCCG)/code_main_tccg_03.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_03.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_4: $(DRIVER_TCCG)/code_main_tccg_04.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_04.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_5: $(DRIVER_TCCG)/code_main_tccg_05.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_05.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_6: $(DRIVER_TCCG)/code_main_tccg_06.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_06.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_7: $(DRIVER_TCCG)/code_main_tccg_07.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_07.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_8: $(DRIVER_TCCG)/code_main_tccg_08.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_08.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_9: $(DRIVER_TCCG)/code_main_tccg_09.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_09.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_10: $(DRIVER_TCCG)/code_main_tccg_10.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_10.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_11: $(DRIVER_TCCG)/code_main_tccg_11.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_11.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_12: $(DRIVER_TCCG)/code_main_tccg_12.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_12.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_13: $(DRIVER_TCCG)/code_main_tccg_13.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_13.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_14: $(DRIVER_TCCG)/code_main_tccg_14.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_14.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_15: $(DRIVER_TCCG)/code_main_tccg_15.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_15.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_16: $(DRIVER_TCCG)/code_main_tccg_16.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_16.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_17: $(DRIVER_TCCG)/code_main_tccg_17.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_17.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_18: $(DRIVER_TCCG)/code_main_tccg_18.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_18.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_19: $(DRIVER_TCCG)/code_main_tccg_19.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_19.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

#
#	TCCG: 4D = 4D * 4D	// 12: 20-30
#
k_tccg_20: $(DRIVER_TCCG)/code_main_tccg_20.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_20.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_21: $(DRIVER_TCCG)/code_main_tccg_21.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_21.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_22: $(DRIVER_TCCG)/code_main_tccg_22.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_22.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_23: $(DRIVER_TCCG)/code_main_tccg_23.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_23.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_24: $(DRIVER_TCCG)/code_main_tccg_24.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_24.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_25: $(DRIVER_TCCG)/code_main_tccg_25.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_25.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_26: $(DRIVER_TCCG)/code_main_tccg_26.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_26.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_27: $(DRIVER_TCCG)/code_main_tccg_27.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_27.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_28: $(DRIVER_TCCG)/code_main_tccg_28.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_28.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_29: $(DRIVER_TCCG)/code_main_tccg_29.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_29.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_30: $(DRIVER_TCCG)/code_main_tccg_30.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_30.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

#
#	TCCG: 6D = 4D * 4D	// 18: 31-48
#
k_tccg_31: $(DRIVER_TCCG)/code_main_tccg_31.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_31.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_32: $(DRIVER_TCCG)/code_main_tccg_32.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_32.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_33: $(DRIVER_TCCG)/code_main_tccg_33.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_33.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_34: $(DRIVER_TCCG)/code_main_tccg_34.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_34.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_35: $(DRIVER_TCCG)/code_main_tccg_35.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_35.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_36: $(DRIVER_TCCG)/code_main_tccg_36.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_36.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_37: $(DRIVER_TCCG)/code_main_tccg_37.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_37.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_38: $(DRIVER_TCCG)/code_main_tccg_38.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_38.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_39: $(DRIVER_TCCG)/code_main_tccg_39.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_39.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_40: $(DRIVER_TCCG)/code_main_tccg_40.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_40.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_41: $(DRIVER_TCCG)/code_main_tccg_41.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_41.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_42: $(DRIVER_TCCG)/code_main_tccg_42.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_42.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_43: $(DRIVER_TCCG)/code_main_tccg_44.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_43.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_44: $(DRIVER_TCCG)/code_main_tccg_44.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_44.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_45: $(DRIVER_TCCG)/code_main_tccg_45.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_45.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_46: $(DRIVER_TCCG)/code_main_tccg_46.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_46.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_47: $(DRIVER_TCCG)/code_main_tccg_47.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_47.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

k_tccg_48: $(DRIVER_TCCG)/code_main_tccg_48.c tccg_kernels.cu memory.cu
	nvcc -O3 -std=c++11 -arch=$(CUDA_ARCH) --use_fast_math $(DRIVER_TCCG)/code_main_tccg_48.c tccg_kernels.cu memory.cu -Xptxas "-v -dlcm=cg" -o $@ $(DEBUG_OPTIONS)

#
#
#
clean:
	rm k_tccg_*
